"""
dailysst.py
-----------
Retrieves the last 7 days of MUR SST 1 km PNG images from NOAA CoastWatch ERDDAP
for the region spanning Atlantic City, NJ to Wilmington, SC.

Dataset : jplMURSST41
Server  : https://coastwatch.pfeg.noaa.gov/erddap
Output  : ./dailysst/  (PNG per day, named sst_YYYY-MM-DD.png)
Manifest: manifest.py  (auto-updated with metadata for every retained file)

Bounding box
  Latitude  : 33.85 N (Wilmington, SC) → 39.36 N (Atlantic City, NJ)
  Longitude : -80.00 W → -73.50 W  (covers the shelf / offshore band)
"""

import os
import sys
import json
import requests
from datetime import date, timedelta
from pathlib import Path

# ── Configuration ────────────────────────────────────────────────────────────

ERDDAP_BASE   = "https://coastwatch.pfeg.noaa.gov/erddap"
DATASET_ID    = "jplMURSST41"
VARIABLE      = "analysed_sst"

# Bounding box: Atlantic City NJ → Wilmington SC (offshore band)
LAT_MIN       = 33.85
LAT_MAX       = 39.36
LON_MIN       = -80.00
LON_MAX       = -73.50

DAYS_BACK     = 7          # how many days to retrieve
OUTPUT_DIR    = Path(__file__).parent / "dailysst"
MANIFEST_PATH = Path(__file__).parent / "manifest.py"

# Image / colour scale settings
COLOR_BAR     = "KT_thermal"   # thermal palette suited to SST
MIN_SST       = 5              # °C  – adjust for season if desired
MAX_SST       = 30             # °C

# ── Helpers ──────────────────────────────────────────────────────────────────

def erddap_image_url(target_date: date) -> str:
    """Build the ERDDAP .png URL for a single day composite."""
    ds = target_date.isoformat()
    # ERDDAP WMS/griddap PNG request
    # Time constraint: exact day (start == stop for a daily composite)
    url = (
        f"{ERDDAP_BASE}/griddap/{DATASET_ID}.png"
        f"?{VARIABLE}"
        f"[({ds}T09:00:00Z):1:({ds}T09:00:00Z)]"   # 09:00 UTC composite
        f"[({LAT_MIN}):1:({LAT_MAX})]"
        f"[({LON_MIN}):1:({LON_MAX})]"
        f"&.draw=surface"
        f"&.vars=longitude%7Clatitude%7C{VARIABLE}"
        f"&.colorBar={COLOR_BAR}%7C%7C%7C{MIN_SST}%7C{MAX_SST}%7C"
        f"&.bgColor=0xffccccff"
    )
    return url


def filename_for(target_date: date) -> Path:
    return OUTPUT_DIR / f"sst_{target_date.isoformat()}.png"


def download_day(target_date: date) -> dict | None:
    """Download SST image for one day.  Returns manifest entry or None on failure."""
    url  = erddap_image_url(target_date)
    dest = filename_for(target_date)

    print(f"  Fetching {target_date} …", end=" ", flush=True)
    try:
        resp = requests.get(url, timeout=120)
        resp.raise_for_status()
        dest.write_bytes(resp.content)
        size = dest.stat().st_size
        print(f"OK  ({size:,} bytes)  → {dest.name}")
        return {
            "date"    : target_date.isoformat(),
            "filename": dest.name,
            "url"     : url,
            "size_bytes": size,
        }
    except requests.HTTPError as exc:
        print(f"HTTP {exc.response.status_code} – skipped")
        return None
    except Exception as exc:
        print(f"ERROR: {exc} – skipped")
        return None


def purge_old_files(keep_dates: set[str]):
    """Remove any sst_*.png files in OUTPUT_DIR not in keep_dates."""
    for p in OUTPUT_DIR.glob("sst_*.png"):
        stem = p.stem          # sst_YYYY-MM-DD
        day  = stem[4:]        # YYYY-MM-DD
        if day not in keep_dates:
            print(f"  Removing stale file: {p.name}")
            p.unlink()


def write_manifest(entries: list[dict]):
    """Write / overwrite manifest.py with current retained files."""
    lines = [
        '"""',
        'manifest.py – auto-generated by dailysst.py',
        'Contains metadata for the SST images currently stored in ./dailysst/',
        '"""',
        "",
        "# Dataset information",
        f'DATASET_ID   = "{DATASET_ID}"',
        f'ERDDAP_BASE  = "{ERDDAP_BASE}"',
        f'VARIABLE     = "{VARIABLE}"',
        "",
        "# Bounding box",
        f"LAT_MIN      = {LAT_MIN}",
        f"LAT_MAX      = {LAT_MAX}",
        f"LON_MIN      = {LON_MIN}",
        f"LON_MAX      = {LON_MAX}",
        "",
        "# Files retained (last 7 days)",
        "FILES = " + json.dumps(entries, indent=4),
        "",
    ]
    MANIFEST_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n  manifest.py updated with {len(entries)} entries.")


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    today      = date.today()
    target_days = [today - timedelta(days=i) for i in range(1, DAYS_BACK + 1)]
    keep_dates  = {d.isoformat() for d in target_days}

    print(f"\nMUR SST – retrieving last {DAYS_BACK} days")
    print(f"Region  : {LAT_MIN}°N–{LAT_MAX}°N  |  {LON_MIN}°W–{LON_MAX}°W")
    print(f"Output  : {OUTPUT_DIR.resolve()}\n")

    entries = []
    for day in sorted(target_days):
        entry = download_day(day)
        if entry:
            entries.append(entry)

    # Remove files older than 7 days
    purge_old_files(keep_dates)

    # Update manifest
    write_manifest(sorted(entries, key=lambda e: e["date"]))

    print(f"\nDone. {len(entries)} file(s) stored in {OUTPUT_DIR}/\n")


if __name__ == "__main__":
    main()
