"""
manifest.py – auto-generated by dailysst.py
Contains metadata for the SST images currently stored in ./dailysst/

Run dailysst.py to refresh this file.
"""

# Dataset information
DATASET_ID   = "jplMURSST41"
ERDDAP_BASE  = "https://coastwatch.pfeg.noaa.gov/erddap"
VARIABLE     = "analysed_sst"

# Bounding box
LAT_MIN      = 33.85
LAT_MAX      = 39.36
LON_MIN      = -80.00
LON_MAX      = -73.50

# Files retained (last 7 days)
# This section is overwritten each time dailysst.py runs.
FILES = []
